#!env bash
set -e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

cd $DIR

PROGRAMS="$(echo "$(sed 's/\[features\]/%/g' Cargo.toml | tr -d $'\n' | cut -d'%' -f2 | sed 's/\]\[/%/g' | cut -d'%' -f1)]" | sed 's/ = \[\]/\n/g' | xargs echo -n)"
NEW='--new'
WRITE='--write'
if [ "$1" = "" ]; then
    echo "$(cat << EOM
ESP lights remote programming tool

USAGE:
    program [OPTIONS] [PROGRAM]

OPTIONS:
    --new [PROGRAM]   Create a new program from template

PROGRAMS:
EOM
)"
    echo "    $(echo $PROGRAMS | sed 's/ /\n    /g')"
    exit
fi
if [ "$2" = "$WRITE" ]; then
    cd write
    cargo build -p write --example $1
    ../target/debug/examples/$1
    exit
fi
if [ "$1" = "$NEW" ];
then
    if [ "$2" == "" ]; then
        echo "Program name must be non-empty"
        exit
    fi
    FILE="src/programs/$(echo $2).rs"
    if test -f "$FILE"; then
        echo "Program \"$2\" already exists"
        exit
    fi
    touch $FILE
    cat << EOM > $FILE
use core::{future::Future, iter::repeat};

use crate::util::next_tick;

pub type Program = impl Future<Output = ()>;

#[allow(dead_code)]
pub unsafe fn $2() -> Program {
    async move {
        let mut leds = crate::leds();
        leds.fill_from(repeat([255, 255, 255]));

        loop {
            next_tick().await;
        }
    }
}
EOM
    exit
fi
RUSTFLAGS="-C link-args=-zstack-size=32768" cargo build --example wasm --target wasm32-unknown-unknown --release --features $1 --no-default-features
cat target/wasm32-unknown-unknown/release/examples/wasm.wasm | wasm-opt -Oz -o build.wasm
SECTION_FOUND="$(wasm-objdump -j custom_discard -x build.wasm 2>&1 | grep "Section not found" || :)"
if [ "$SECTION_FOUND" = "" ]; then
    mkdir -p write/programs
    FILE="write/examples/$1.rs"
    if [ ! -f "$FILE" ]; then
        touch $FILE
        cat << EOM > $FILE
use ::write::send;

#[async_std::main]
async fn main() {
    send(vec![]).await.unwrap();
}
EOM
        touch $FILE
    fi
fi
wasm-strip build.wasm
if [ "$ESP_AUTH_TOKEN" = "" ]; then
    echo "ERROR: ESP_AUTH_TOKEN not specified, quitting"
    rm build.wasm
    exit
fi
curl --data-binary "@build.wasm" http://lightsmanager.syntacticsugarglider.com/upload/$ESP_AUTH_TOKEN/192.168.4.203
echo "sent $(cat build.wasm | wc -c) bytes"
rm build.wasm
